version: '3.8'
volumes:
  datafiles:
services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./src:/var/www/html/
    restart: always
  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=example
      - MYSQL_DBNAME=salary
    ports:
      - 8080:8080
    depends_on:
      - mysql
